/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    VpiChevronLeft: typeof import('~icons/vpi/chevron-left')['default']
    VpiChevronRight: typeof import('~icons/vpi/chevron-right')['default']
    VpiEllipsis: typeof import('~icons/vpi/ellipsis')['default']
  }
}
