/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    VpiBookmark: typeof import('~icons/vpi/bookmark')['default']
    VpiChevronLeft: typeof import('~icons/vpi/chevron-left')['default']
    VpiChevronRight: typeof import('~icons/vpi/chevron-right')['default']
    VpiClock: typeof import('~icons/vpi/clock')['default']
    VpiClose: typeof import('~icons/vpi/close')['default']
    VpiEllipsis: typeof import('~icons/vpi/ellipsis')['default']
    VpiTag: typeof import('~icons/vpi/tag')['default']
    VpiUser: typeof import('~icons/vpi/user')['default']
  }
}
